-- ============================================================
-- Rusti Shack — products table
-- Run this entire file in the Supabase SQL editor
-- ============================================================

CREATE TABLE IF NOT EXISTS products (
  sku          text PRIMARY KEY,
  name         text NOT NULL,
  category     text NOT NULL,
  subcategory  text NOT NULL,
  price        numeric(10,2) NOT NULL CHECK (price >= 0),
  availability text NOT NULL CHECK (availability IN ('Sale only', 'Both')),
  colors       jsonb NOT NULL DEFAULT '[]',
  sizes        jsonb NOT NULL DEFAULT '[]',
  variants     jsonb NOT NULL DEFAULT '[]'
);

-- §4 SECURITY.md: RLS enabled immediately, before any data is inserted
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Public may read products; no public writes ever
DROP POLICY IF EXISTS "products_public_select" ON products;
CREATE POLICY "products_public_select" ON products
  FOR SELECT USING (true);

-- ── Seed data (safe to re-run: upserts on conflict) ──
INSERT INTO products (sku, name, category, subcategory, price, availability, colors, sizes, variants)
VALUES
  ('SNK-001','Reef Explorer Snorkel Mask','Snorkel & Dive','Masks',42.99,'Both','["Black", "Clear"]','["L", "M", "S"]','[{"sku": "SNK-001-S-CLR", "size": "S", "color": "Clear", "gender": "U"}, {"sku": "SNK-001-M-CLR", "size": "M", "color": "Clear", "gender": "U"}, {"sku": "SNK-001-L-CLR", "size": "L", "color": "Clear", "gender": "U"}, {"sku": "SNK-001-S-BLK", "size": "S", "color": "Black", "gender": "U"}, {"sku": "SNK-001-M-BLK", "size": "M", "color": "Black", "gender": "U"}, {"sku": "SNK-001-L-BLK", "size": "L", "color": "Black", "gender": "U"}]'),
  ('SNK-003','Junior Snorkel Set (Kids)','Snorkel & Dive','Sets',34.99,'Both','["Aqua", "Pink"]','["Age 4-7", "Age 8-12"]','[{"sku": "SNK-003-K4-7-AQUA", "size": "Age 4-7", "color": "Aqua", "gender": "U"}, {"sku": "SNK-003-K4-7-PINK", "size": "Age 4-7", "color": "Pink", "gender": "U"}, {"sku": "SNK-003-K8-12-AQUA", "size": "Age 8-12", "color": "Aqua", "gender": "U"}, {"sku": "SNK-003-K8-12-PINK", "size": "Age 8-12", "color": "Pink", "gender": "U"}]'),
  ('FIN-001','Open-Heel Dive Fins','Snorkel & Dive','Fins',79.0,'Both','["Black"]','["L (M9-10)", "M (W8-9 / M7-8)", "S (W6-7)", "XL (M11-12)"]','[{"sku": "FIN-001-S", "size": "S (W6-7)", "color": "Black", "gender": "U"}, {"sku": "FIN-001-M", "size": "M (W8-9 / M7-8)", "color": "Black", "gender": "U"}, {"sku": "FIN-001-L", "size": "L (M9-10)", "color": "Black", "gender": "U"}, {"sku": "FIN-001-XL", "size": "XL (M11-12)", "color": "Black", "gender": "U"}]'),
  ('FIN-003','Kids Swim Fins','Snorkel & Dive','Fins',29.99,'Both','["Aqua"]','["Kids M", "Kids S"]','[{"sku": "FIN-003-S", "size": "Kids S", "color": "Aqua", "gender": "U"}, {"sku": "FIN-003-M", "size": "Kids M", "color": "Aqua", "gender": "U"}]'),
  ('BCH-003','Beach Towel Tropical Print','Beach Essentials','Towels',24.99,'Both','["Palm Print", "Reef Print", "Sunset Print"]','["Standard"]','[{"sku": "BCH-003-SUNSET", "size": "Standard", "color": "Sunset Print", "gender": "U"}, {"sku": "BCH-003-REEF", "size": "Standard", "color": "Reef Print", "gender": "U"}, {"sku": "BCH-003-PALM", "size": "Standard", "color": "Palm Print", "gender": "U"}]'),
  ('SUR-003','Beginner Foam Surfboard','Surfing','Surfboards',279.0,'Both','["Blue"]','["7ft", "8ft", "9ft"]','[{"sku": "SUR-003-7FT", "size": "7ft", "color": "Blue", "gender": "U"}, {"sku": "SUR-003-8FT", "size": "8ft", "color": "Blue", "gender": "U"}, {"sku": "SUR-003-9FT", "size": "9ft", "color": "Blue", "gender": "U"}]'),
  ('APP-001','Tide & Tempo Logo Tee','Apparel','Shirts',24.99,'Sale only','["Teal"]','["L", "M", "S", "XL", "XS"]','[{"sku": "APP-001-XS-M", "size": "XS", "color": "Teal", "gender": "M"}, {"sku": "APP-001-XS-W", "size": "XS", "color": "Teal", "gender": "W"}, {"sku": "APP-001-S-M", "size": "S", "color": "Teal", "gender": "M"}, {"sku": "APP-001-S-W", "size": "S", "color": "Teal", "gender": "W"}, {"sku": "APP-001-M-M", "size": "M", "color": "Teal", "gender": "M"}, {"sku": "APP-001-M-W", "size": "M", "color": "Teal", "gender": "W"}, {"sku": "APP-001-L-M", "size": "L", "color": "Teal", "gender": "M"}, {"sku": "APP-001-L-W", "size": "L", "color": "Teal", "gender": "W"}, {"sku": "APP-001-XL-M", "size": "XL", "color": "Teal", "gender": "M"}, {"sku": "APP-001-XL-W", "size": "XL", "color": "Teal", "gender": "W"}]'),
  ('SNK-002','Pro Anti-Fog Snorkel Mask','Snorkel & Dive','Masks',58.0,'Both','["Black", "Clear"]','["L", "M", "S"]','[{"sku": "SNK-002-S-CLR", "size": "S", "color": "Clear", "gender": "U"}, {"sku": "SNK-002-M-CLR", "size": "M", "color": "Clear", "gender": "U"}, {"sku": "SNK-002-L-CLR", "size": "L", "color": "Clear", "gender": "U"}, {"sku": "SNK-002-S-BLK", "size": "S", "color": "Black", "gender": "U"}, {"sku": "SNK-002-M-BLK", "size": "M", "color": "Black", "gender": "U"}, {"sku": "SNK-002-L-BLK", "size": "L", "color": "Black", "gender": "U"}]'),
  ('SNK-004','Adult Snorkel Set','Snorkel & Dive','Sets',64.99,'Both','["Black"]','["L", "M", "S"]','[{"sku": "SNK-004-S", "size": "S", "color": "Black", "gender": "U"}, {"sku": "SNK-004-M", "size": "M", "color": "Black", "gender": "U"}, {"sku": "SNK-004-L", "size": "L", "color": "Black", "gender": "U"}]'),
  ('FIN-002','Travel Snorkel Fins','Snorkel & Dive','Fins',49.99,'Both','["Black"]','["L (M9-10)", "M (W8-9 / M7-8)", "S (W6-7)", "XL (M11-12)"]','[{"sku": "FIN-002-S", "size": "S (W6-7)", "color": "Black", "gender": "U"}, {"sku": "FIN-002-M", "size": "M (W8-9 / M7-8)", "color": "Black", "gender": "U"}, {"sku": "FIN-002-L", "size": "L (M9-10)", "color": "Black", "gender": "U"}, {"sku": "FIN-002-XL", "size": "XL (M11-12)", "color": "Black", "gender": "U"}]'),
  ('WET-001','3mm Shorty Wetsuit','Snorkel & Dive','Wetsuits',109.0,'Both','["Black"]','["L", "M", "S", "XL"]','[{"sku": "WET-001-S-M", "size": "S", "color": "Black", "gender": "M"}, {"sku": "WET-001-S-W", "size": "S", "color": "Black", "gender": "W"}, {"sku": "WET-001-M-M", "size": "M", "color": "Black", "gender": "M"}, {"sku": "WET-001-M-W", "size": "M", "color": "Black", "gender": "W"}, {"sku": "WET-001-L-M", "size": "L", "color": "Black", "gender": "M"}, {"sku": "WET-001-L-W", "size": "L", "color": "Black", "gender": "W"}, {"sku": "WET-001-XL-M", "size": "XL", "color": "Black", "gender": "M"}, {"sku": "WET-001-XL-W", "size": "XL", "color": "Black", "gender": "W"}]'),
  ('WET-002','Rashguard Long Sleeve','Apparel','Rashguards',32.99,'Sale only','["Coral", "Navy"]','["L", "M", "S", "XL"]','[{"sku": "WET-002-S-M", "size": "S", "color": "Navy", "gender": "M"}, {"sku": "WET-002-S-W", "size": "S", "color": "Coral", "gender": "W"}, {"sku": "WET-002-M-M", "size": "M", "color": "Navy", "gender": "M"}, {"sku": "WET-002-M-W", "size": "M", "color": "Coral", "gender": "W"}, {"sku": "WET-002-L-M", "size": "L", "color": "Navy", "gender": "M"}, {"sku": "WET-002-L-W", "size": "L", "color": "Coral", "gender": "W"}, {"sku": "WET-002-XL-M", "size": "XL", "color": "Navy", "gender": "M"}, {"sku": "WET-002-XL-W", "size": "XL", "color": "Coral", "gender": "W"}]'),
  ('APP-002','Apo Island Souvenir Tee','Apparel','Shirts',26.99,'Sale only','["Sand"]','["L", "M", "S", "XL", "XS"]','[{"sku": "APP-002-XS-M", "size": "XS", "color": "Sand", "gender": "M"}, {"sku": "APP-002-XS-W", "size": "XS", "color": "Sand", "gender": "W"}, {"sku": "APP-002-S-M", "size": "S", "color": "Sand", "gender": "M"}, {"sku": "APP-002-S-W", "size": "S", "color": "Sand", "gender": "W"}, {"sku": "APP-002-M-M", "size": "M", "color": "Sand", "gender": "M"}, {"sku": "APP-002-M-W", "size": "M", "color": "Sand", "gender": "W"}, {"sku": "APP-002-L-M", "size": "L", "color": "Sand", "gender": "M"}, {"sku": "APP-002-L-W", "size": "L", "color": "Sand", "gender": "W"}, {"sku": "APP-002-XL-M", "size": "XL", "color": "Sand", "gender": "M"}, {"sku": "APP-002-XL-W", "size": "XL", "color": "Sand", "gender": "W"}]'),
  ('BCH-004','Microfiber Quick-Dry Towel','Beach Essentials','Towels',28.0,'Both','["Black", "Blue", "Coral"]','["L (80x160cm)", "M (60x120cm)"]','[{"sku": "BCH-004-M-BLU", "size": "M (60x120cm)", "color": "Blue", "gender": "U"}, {"sku": "BCH-004-L-BLU", "size": "L (80x160cm)", "color": "Blue", "gender": "U"}, {"sku": "BCH-004-M-CRL", "size": "M (60x120cm)", "color": "Coral", "gender": "U"}, {"sku": "BCH-004-L-CRL", "size": "L (80x160cm)", "color": "Coral", "gender": "U"}, {"sku": "BCH-004-M-BLK", "size": "M (60x120cm)", "color": "Black", "gender": "U"}, {"sku": "BCH-004-L-BLK", "size": "L (80x160cm)", "color": "Black", "gender": "U"}]'),
  ('BCH-012','Cooler Bag Insulated 24L','Beach Essentials','Coolers',58.0,'Both','["Blue"]','["16 L", "24 L", "40 L"]','[{"sku": "BCH-012-16L", "size": "16 L", "color": "Blue", "gender": "U"}, {"sku": "BCH-012-24L", "size": "24 L", "color": "Blue", "gender": "U"}, {"sku": "BCH-012-40L", "size": "40 L", "color": "Blue", "gender": "U"}]'),
  ('APP-003','Boardshorts — Mens','Apparel','Bottoms',44.99,'Sale only','["Navy"]','["28", "30", "32", "34", "36", "38", "40"]','[{"sku": "APP-003-28", "size": "28", "color": "Navy", "gender": "M"}, {"sku": "APP-003-30", "size": "30", "color": "Navy", "gender": "M"}, {"sku": "APP-003-32", "size": "32", "color": "Navy", "gender": "M"}, {"sku": "APP-003-34", "size": "34", "color": "Navy", "gender": "M"}, {"sku": "APP-003-36", "size": "36", "color": "Navy", "gender": "M"}, {"sku": "APP-003-38", "size": "38", "color": "Navy", "gender": "M"}, {"sku": "APP-003-40", "size": "40", "color": "Navy", "gender": "M"}]'),
  ('APP-004','Bikini Set — Womens','Apparel','Swimwear',54.0,'Sale only','["Aqua", "Black", "Coral", "Tropical Print"]','["L", "M", "S", "XL", "XS"]','[{"sku": "APP-004-XS-COR", "size": "XS", "color": "Coral", "gender": "W"}, {"sku": "APP-004-XS-AQU", "size": "XS", "color": "Aqua", "gender": "W"}, {"sku": "APP-004-XS-BLA", "size": "XS", "color": "Black", "gender": "W"}, {"sku": "APP-004-XS-TRO", "size": "XS", "color": "Tropical Print", "gender": "W"}, {"sku": "APP-004-S-COR", "size": "S", "color": "Coral", "gender": "W"}, {"sku": "APP-004-S-AQU", "size": "S", "color": "Aqua", "gender": "W"}, {"sku": "APP-004-S-BLA", "size": "S", "color": "Black", "gender": "W"}, {"sku": "APP-004-S-TRO", "size": "S", "color": "Tropical Print", "gender": "W"}, {"sku": "APP-004-M-COR", "size": "M", "color": "Coral", "gender": "W"}, {"sku": "APP-004-M-AQU", "size": "M", "color": "Aqua", "gender": "W"}, {"sku": "APP-004-M-BLA", "size": "M", "color": "Black", "gender": "W"}, {"sku": "APP-004-M-TRO", "size": "M", "color": "Tropical Print", "gender": "W"}, {"sku": "APP-004-L-COR", "size": "L", "color": "Coral", "gender": "W"}, {"sku": "APP-004-L-AQU", "size": "L", "color": "Aqua", "gender": "W"}, {"sku": "APP-004-L-BLA", "size": "L", "color": "Black", "gender": "W"}, {"sku": "APP-004-L-TRO", "size": "L", "color": "Tropical Print", "gender": "W"}, {"sku": "APP-004-XL-COR", "size": "XL", "color": "Coral", "gender": "W"}, {"sku": "APP-004-XL-AQU", "size": "XL", "color": "Aqua", "gender": "W"}, {"sku": "APP-004-XL-BLA", "size": "XL", "color": "Black", "gender": "W"}, {"sku": "APP-004-XL-TRO", "size": "XL", "color": "Tropical Print", "gender": "W"}]'),
  ('APP-005','One-Piece Swimsuit','Apparel','Swimwear',58.0,'Sale only','["Black", "Coral", "Navy"]','["L", "M", "S", "XL"]','[{"sku": "APP-005-S-BLA", "size": "S", "color": "Black", "gender": "W"}, {"sku": "APP-005-S-NAV", "size": "S", "color": "Navy", "gender": "W"}, {"sku": "APP-005-S-COR", "size": "S", "color": "Coral", "gender": "W"}, {"sku": "APP-005-M-BLA", "size": "M", "color": "Black", "gender": "W"}, {"sku": "APP-005-M-NAV", "size": "M", "color": "Navy", "gender": "W"}, {"sku": "APP-005-M-COR", "size": "M", "color": "Coral", "gender": "W"}, {"sku": "APP-005-L-BLA", "size": "L", "color": "Black", "gender": "W"}, {"sku": "APP-005-L-NAV", "size": "L", "color": "Navy", "gender": "W"}, {"sku": "APP-005-L-COR", "size": "L", "color": "Coral", "gender": "W"}, {"sku": "APP-005-XL-BLA", "size": "XL", "color": "Black", "gender": "W"}, {"sku": "APP-005-XL-NAV", "size": "XL", "color": "Navy", "gender": "W"}, {"sku": "APP-005-XL-COR", "size": "XL", "color": "Coral", "gender": "W"}]'),
  ('APP-007','Flip Flops Tropical','Apparel','Footwear',14.99,'Sale only','["Tropical"]','["K2-4", "M11-12", "M9-10", "W6-7", "W8-9"]','[{"sku": "APP-007-W6-7", "size": "W6-7", "color": "Tropical", "gender": "W"}, {"sku": "APP-007-W8-9", "size": "W8-9", "color": "Tropical", "gender": "W"}, {"sku": "APP-007-M9-10", "size": "M9-10", "color": "Tropical", "gender": "M"}, {"sku": "APP-007-M11-12", "size": "M11-12", "color": "Tropical", "gender": "M"}, {"sku": "APP-007-K2-4", "size": "K2-4", "color": "Tropical", "gender": "U"}]'),
  ('SUR-004','Surf Leash 8ft','Surfing','Accessories',22.5,'Sale only','["Black"]','["6 ft", "7 ft", "8 ft", "9 ft"]','[{"sku": "SUR-004-6FT", "size": "6 ft", "color": "Black", "gender": "U"}, {"sku": "SUR-004-7FT", "size": "7 ft", "color": "Black", "gender": "U"}, {"sku": "SUR-004-8FT", "size": "8 ft", "color": "Black", "gender": "U"}, {"sku": "SUR-004-9FT", "size": "9 ft", "color": "Black", "gender": "U"}]'),
  ('SUR-006','Skim Board Pro','Surfing','Skimboards',89.0,'Both','["Tropical"]','["Adult", "Youth"]','[{"sku": "SUR-006-YTH", "size": "Youth", "color": "Tropical", "gender": "U"}, {"sku": "SUR-006-ADL", "size": "Adult", "color": "Tropical", "gender": "U"}]'),
  ('KIT-002','Kitesurf Harness','Surfing','Kitesurf',139.0,'Sale only','["Black"]','["L", "M", "S", "XL"]','[{"sku": "KIT-002-S", "size": "S", "color": "Black", "gender": "U"}, {"sku": "KIT-002-M", "size": "M", "color": "Black", "gender": "U"}, {"sku": "KIT-002-L", "size": "L", "color": "Black", "gender": "U"}, {"sku": "KIT-002-XL", "size": "XL", "color": "Black", "gender": "U"}]'),
  ('APP-006','UV Hat Wide Brim','Apparel','Hats',28.0,'Sale only','["Black", "Natural"]','["L/XL", "S/M"]','[{"sku": "APP-006-SM-NAT", "size": "S/M", "color": "Natural", "gender": "U"}, {"sku": "APP-006-SM-BLK", "size": "S/M", "color": "Black", "gender": "U"}, {"sku": "APP-006-LXL-NAT", "size": "L/XL", "color": "Natural", "gender": "U"}, {"sku": "APP-006-LXL-BLK", "size": "L/XL", "color": "Black", "gender": "U"}]'),
  ('KIT-001','Beginner Kitesurf Kit','Surfing','Kitesurf',1099.0,'Sale only','["Blue", "Red", "Yellow"]','["12 m2", "7 m2", "9 m2"]','[{"sku": "KIT-001-7M", "size": "7 m2", "color": "Red", "gender": "U"}, {"sku": "KIT-001-9M", "size": "9 m2", "color": "Blue", "gender": "U"}, {"sku": "KIT-001-12M", "size": "12 m2", "color": "Yellow", "gender": "U"}]'),
  ('BCH-009','Polarized Sunglasses','Beach Essentials','Eyewear',39.99,'Sale only','["Aviator/Black", "Aviator/Gold", "Cat-Eye/Tortoise", "Sport/Black", "Wayfarer/Black", "Wayfarer/Tortoise"]','["One Size"]','[{"sku": "BCH-009-AVI-BLK", "size": "One Size", "color": "Aviator/Black", "gender": "M"}, {"sku": "BCH-009-AVI-GLD", "size": "One Size", "color": "Aviator/Gold", "gender": "U"}, {"sku": "BCH-009-WAY-BLK", "size": "One Size", "color": "Wayfarer/Black", "gender": "U"}, {"sku": "BCH-009-WAY-TOR", "size": "One Size", "color": "Wayfarer/Tortoise", "gender": "U"}, {"sku": "BCH-009-SPT-BLK", "size": "One Size", "color": "Sport/Black", "gender": "M"}, {"sku": "BCH-009-CAT-TOR", "size": "One Size", "color": "Cat-Eye/Tortoise", "gender": "W"}]'),
  ('BCH-011','Reef Walker Water Shoes','Beach Essentials','Footwear',38.0,'Both','["Aqua", "Black"]','["Kids 2-4", "M11-12", "M9-10", "W6-7", "W8-9"]','[{"sku": "BCH-011-W6-7", "size": "W6-7", "color": "Black", "gender": "W"}, {"sku": "BCH-011-W8-9", "size": "W8-9", "color": "Black", "gender": "W"}, {"sku": "BCH-011-M9-10", "size": "M9-10", "color": "Black", "gender": "M"}, {"sku": "BCH-011-M11-12", "size": "M11-12", "color": "Black", "gender": "M"}, {"sku": "BCH-011-K2-4", "size": "Kids 2-4", "color": "Aqua", "gender": "U"}]')
ON CONFLICT (sku) DO UPDATE SET
  name=EXCLUDED.name, category=EXCLUDED.category,
  subcategory=EXCLUDED.subcategory, price=EXCLUDED.price,
  availability=EXCLUDED.availability, colors=EXCLUDED.colors,
  sizes=EXCLUDED.sizes, variants=EXCLUDED.variants;

-- Verify
SELECT sku, name, price FROM products ORDER BY category, subcategory;